name: flash_staff
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  # CORE
  core_dependency:
    path: '../../core/core_dependency'

  core_router:
    path: '../../core/core_router'

  core_data:
    path: '../../core/core_data'

  core_ui:
    path: '../../core/core_ui'

# SERVICE

  auth_service:
    path: '../../services/auth'

  customers_service:
    path: '../../services/customers'

  subscription_service:
    path: '../../services/subscription'

  firebase_service:
    path: '../../services/firebase'

  ticket_service:
    path: '../../services/ticket'

# FEATURE

  delivery:
    path: '../../features/delivery'

  menu:
    path: '../../features/menu'
  
  floor_table:
    path: '../../features/floor_table'

  orders:
    path: '../../features/orders'

  setting:
    path: '../../features/setting'

  authentication:
    path: '../../features/authentication'
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: null
  build_runner: null
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0
  injectable_generator: null
  retrofit_generator:
  envied_generator:
  

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  
  #   - family: SF Pro Text
  #     fonts:
  #       - asset: packages/core_ui/fonts/SF-Pro-Text-Ultralight.otf
  #         weight: 100
  #       - asset: packages/core_ui/fonts/SF-Pro-Text-Thin.otf
  #         weight: 200
  #       - asset: packages/core_ui/fonts/SF-Pro-Text-Light.otf
  #         weight: 300
  #       - asset: packages/core_ui/fonts/SF-Pro-Text-Regular.otf
  #         weight: 400
  #       - asset: packages/core_ui/fonts/SF-Pro-Text-Medium.otf
  #         weight: 500
  #       - asset: packages/core_ui/fonts/SF-Pro-Text-Semibold.otf
  #         weight: 600
  #       - asset: packages/core_ui/fonts/SF-Pro-Text-Bold.otf
  #         weight: 700
  #       - asset: packages/core_ui/fonts/SF-Pro-Text-Heavy.otf
  #         weight: 800
  #       - asset: packages/core_ui/fonts/SF-Pro-Text-Black.otf
  #         weight: 900
  


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
