name: core_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1
  flutter_sheet_localization:
    git:
      url: git@github.com:hacnguyen1412/flutter_sheet_localization.git
      path: flutter_sheet_localization
  fl_chart: ^0.62.0
  intl: ^0.18.0
  flutter_design_system: ^1.1.2
  expandable: ^5.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_slidable: ^3.0.0
  easy_sidemenu: ^0.4.1+1
  flutter_animated_dialog: ^2.0.1
  mirai_dropdown_menu: ^0.0.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:
  flutter_sheet_localization_generator:
    git:
      url: git@github.com:hacnguyen1412/flutter_sheet_localization.git
      path: flutter_sheet_localization_generator

flutter_gen:
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/
    - assets/fonts/

  fonts:
  
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-Black.otf
          weight: 900
  